"""runs: characters, runs, tasks, blackboard, findings, clusters

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-05 23:45:55.858028
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('folder_path', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_characters')),
    sa.UniqueConstraint('slug', name=op.f('uq_characters_slug'))
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('character_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('profile_md', sa.Text(), nullable=False),
    sa.Column('front_matter', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('canonical_image_path', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_character_versions_character_id_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character_versions')),
    sa.UniqueConstraint('character_id', 'version', name=op.f('uq_character_versions_character_id'))
    )
    op.create_index(op.f('ix_character_versions_character_id'), 'character_versions', ['character_id'], unique=False)
    op.create_table('directions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('niche', sa.String(length=128), nullable=True),
    sa.Column('alpha', sa.Integer(), server_default='0', nullable=False),
    sa.Column('beta', sa.Integer(), server_default='0', nullable=False),
    sa.Column('runs_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_directions_character_id_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_directions')),
    sa.UniqueConstraint('character_id', 'key', name=op.f('uq_directions_character_id'))
    )
    op.create_table('seeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('canonical_id', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=16), server_default='profile', nullable=False),
    sa.Column('study', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_seeds_character_id_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seeds')),
    sa.UniqueConstraint('character_id', 'url', name=op.f('uq_seeds_character_id'))
    )
    op.create_table('seen_items',
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('canonical_id', sa.String(length=64), nullable=False),
    sa.Column('first_run_id', sa.UUID(), nullable=True),
    sa.Column('rated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_seen_items_character_id_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'canonical_id', name=op.f('pk_seen_items'))
    )
    op.create_table('taste_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=16), nullable=False),
    sa.Column('source_run_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_taste_profiles_character_id_characters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taste_profiles')),
    sa.UniqueConstraint('character_id', 'version', name=op.f('uq_taste_profiles_character_id'))
    )
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('character_version_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=24), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('explore_ratio_used', sa.Float(), nullable=True),
    sa.Column('current_round', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stop_reason', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_runs_character_id_characters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_version_id'], ['character_versions.id'], name=op.f('fk_runs_character_version_id_character_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs'))
    )
    op.create_index(op.f('ix_runs_state'), 'runs', ['state'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_events_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_run_id'), 'events', ['run_id'], unique=False)
    op.create_table('rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('plan_rejections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_rounds_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rounds')),
    sa.UniqueConstraint('run_id', 'number', name=op.f('uq_rounds_run_id'))
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('round_id', sa.UUID(), nullable=True),
    sa.Column('task_type', sa.String(length=24), nullable=False),
    sa.Column('direction_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(length=16), nullable=True),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('budget', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('state', sa.String(length=16), server_default='queued', nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transcript_path', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.id'], name=op.f('fk_tasks_direction_id_directions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], name=op.f('fk_tasks_round_id_rounds'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_tasks_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index('ix_tasks_queue', 'tasks', ['run_id', 'state', 'not_before'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('canonical_id', sa.String(length=64), nullable=False),
    sa.Column('direction_id', sa.UUID(), nullable=True),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('preliminary_fit', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=24), server_default='pending_analysis', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['videos.canonical_id'], name=op.f('fk_findings_canonical_id_videos')),
    sa.ForeignKeyConstraint(['direction_id'], ['directions.id'], name=op.f('fk_findings_direction_id_directions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_findings_run_id_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_findings_task_id_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_findings')),
    sa.UniqueConstraint('run_id', 'canonical_id', name=op.f('uq_findings_run_id'))
    )
    op.create_index('ix_findings_run_status', 'findings', ['run_id', 'status'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('source_task_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('why', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='new', nullable=False),
    sa.Column('assigned_task_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_leads_run_id_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_task_id'], ['tasks.id'], name=op.f('fk_leads_source_task_id_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads')),
    sa.UniqueConstraint('run_id', 'platform', 'type', 'value', name=op.f('uq_leads_run_id'))
    )
    op.create_table('scope_claims',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_scope_claims_run_id_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_scope_claims_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'platform', 'kind', 'value', name=op.f('pk_scope_claims'))
    )
    op.create_table('finding_scores',
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('fit', sa.Float(), nullable=True),
    sa.Column('fit_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fit_justification', sa.Text(), nullable=True),
    sa.Column('adaptation_idea', sa.Text(), nullable=True),
    sa.Column('feasibility_notes', sa.Text(), nullable=True),
    sa.Column('niche_guess', sa.String(length=128), nullable=True),
    sa.Column('feasibility', sa.Float(), nullable=True),
    sa.Column('momentum', sa.Float(), nullable=True),
    sa.Column('freshness', sa.Float(), nullable=True),
    sa.Column('overall', sa.Float(), nullable=True),
    sa.Column('analyst_provider', sa.String(length=32), nullable=True),
    sa.Column('analyst_model', sa.String(length=128), nullable=True),
    sa.Column('cross_fit', sa.Float(), nullable=True),
    sa.Column('cross_provider', sa.String(length=32), nullable=True),
    sa.Column('cross_justification', sa.Text(), nullable=True),
    sa.Column('disagreement', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_finding_scores_finding_id_findings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('finding_id', name=op.f('pk_finding_scores'))
    )
    op.create_table('trend_clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('best_finding_id', sa.UUID(), nullable=True),
    sa.Column('member_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('sound_id', sa.String(length=128), nullable=True),
    sa.Column('overall', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['best_finding_id'], ['findings.id'], name=op.f('fk_trend_clusters_best_finding_id_findings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_trend_clusters_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trend_clusters'))
    )
    op.create_index(op.f('ix_trend_clusters_run_id'), 'trend_clusters', ['run_id'], unique=False)
    op.create_table('trend_members',
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['trend_clusters.id'], name=op.f('fk_trend_members_cluster_id_trend_clusters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], name=op.f('fk_trend_members_finding_id_findings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cluster_id', 'finding_id', name=op.f('pk_trend_members'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trend_members')
    op.drop_index(op.f('ix_trend_clusters_run_id'), table_name='trend_clusters')
    op.drop_table('trend_clusters')
    op.drop_table('finding_scores')
    op.drop_table('scope_claims')
    op.drop_table('leads')
    op.drop_index('ix_findings_run_status', table_name='findings')
    op.drop_table('findings')
    op.drop_index('ix_tasks_queue', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('rounds')
    op.drop_index(op.f('ix_events_run_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_runs_state'), table_name='runs')
    op.drop_table('runs')
    op.drop_table('taste_profiles')
    op.drop_table('seen_items')
    op.drop_table('seeds')
    op.drop_table('directions')
    op.drop_index(op.f('ix_character_versions_character_id'), table_name='character_versions')
    op.drop_table('character_versions')
    op.drop_table('settings')
    op.drop_table('characters')
    # ### end Alembic commands ###
