"""feedback and briefs

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-06 00:38:14.206799
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_feedback',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('satisfaction', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('contributions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('satisfaction between 1 and 10', name=op.f('ck_run_feedback_satisfaction')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_run_feedback_run_id_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_run_feedback'))
    )
    op.create_table('briefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('character_version_id', sa.UUID(), nullable=True),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_version_id'], ['character_versions.id'], name=op.f('fk_briefs_character_version_id_character_versions')),
    sa.ForeignKeyConstraint(['cluster_id'], ['trend_clusters.id'], name=op.f('fk_briefs_cluster_id_trend_clusters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_briefs')),
    sa.UniqueConstraint('cluster_id', name=op.f('uq_briefs_cluster_id'))
    )
    op.create_table('card_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.String(length=8), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("rating in ('up', 'down', 'skip')", name=op.f('ck_card_feedback_rating')),
    sa.ForeignKeyConstraint(['cluster_id'], ['trend_clusters.id'], name=op.f('fk_card_feedback_cluster_id_trend_clusters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card_feedback')),
    sa.UniqueConstraint('cluster_id', name=op.f('uq_card_feedback_cluster_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_feedback')
    op.drop_table('briefs')
    op.drop_table('run_feedback')
    # ### end Alembic commands ###
